### ISSUE TITLE
websockets not working

### ISSUE THREAD

**Issue by kiranmaya** [ridicoulous/LiquidQuoine.Net#58]
web sockets not working.

**Comment by mclean25** [comment]
I'm also having this issue FYI.

**Comment by ridicoulous** [comment]
Hi guys. I'm a quite busy and can not resolve this issue right now. Current version of websocket connection was implemented by reverse engineering front-end, when official docs was does not contains any info about websockets, only http api.

**Comment by ridicoulous** [comment]
it was very simply, only need to change default ws endpoint. Subscribing to order book sides and trades by symbol works as expected. All other enpoints including private (which depends at auth implementation) is not checked now. as you already know, pull requests are welcome=)

**Comment by ridicoulous** [comment]
@mclean25 can you test version 0.3.6? (it will be pushed on nuget soon). I implemented socket auth and subscribing to user executions and orders.

**Comment by mclean25** [comment]
I'm testing with `0.3.6` by trying to subscribe to `SubscribeToOrderBookSide`, and it still isn't working; although it does say now that the connection is created:

```cs
SocketClient.SubscribeToOrderBookSide(
                symbol: "btcusd",
                side: OrderSide.Buy,
                onData: (update, side, timestamp) => HandleOrderbookUpdate(
                    update, side, timestamp)
```

```
2020-08-27 17:58:26:658 | Debug | Socket client PusherClient.Connection state setted to Connecting
```

**Comment by mclean25** [comment]
What's really strange is that I can get this working when I pull the `master` branch of this repo and subscribe to orderbooks in the console client you have, but it won't work in my own repo even if I copy the exact same code from the example. Still under investigation...

**Comment by ridicoulous** [comment]
@mclean25 I use latest version and it works as expected
```csharp
var liquidSocket = new LiquidQuoineSocketClient(new LiquidQuoineSocketClientOptions());
liquidSocket .SubscribeToOrderBookSide("btcusd", LiquidQuoine.Net.Objects.OrderSide.Buy, (update, side, symbol) => { Console.WriteLine($"{symbol} - {side}: {update[0].Price}"); });
```
```
btcusd - Buy: 11450.37000
btcusd - Buy: 11450.37000
btcusd - Buy: 11450.37000
btcusd - Buy: 11450.37000
```

**Comment by mclean25** [comment]
Yup, seems to be working correctly for me as well. I think this issue can be closed. Thanks for fixing that 👍
